
server:
   port: 8090

#spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/ddp?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: a2468*
#    jpa:
#      hibernate:
#        ddl-auto: update


#mybatis-plus:
#  # Search for the specified package alias
#  typeAliasesPackage: com.example.**.domain
#  # Configure mapper scanning to find all mapper.xml mapping files
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # Load the global configuration file
#  configLocation: classpath:mybatis/mybatis-config.xml



